[package]
name = "audioviz"
version = "0.1.1"
authors = ["Luca <b.lucab@gmail.com>"]
edition = "2018"
license = "MIT"
description = "audioviz is a audio libary written in pure rust that makes raw audiodata using some algorithms like FFT visually more appealing"
readme = "README.md"
repository = "https://github.com/BrunoWallner/audioviz"
keywords = ["audio", "FFT", "conversion"]
categories = ["multimedia::audio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "6.0.1"
apodize = "1.0.0"
